# Establecer la imagen base de Node.js
FROM node:22

# Creamos un directorio en el contenedor 
RUN mkdir -p /home/app
# Crear un directorio de trabajo en el contenedor
WORKDIR /home/app

# Copiar los archivos del backend al contenedor
COPY package.json .
COPY src/backend/ .

# Instalar las dependencias
RUN npm install
RUN npm install -g nodemon
# Exponer el puerto (ajústalo según tus necesidades)
EXPOSE 4000

# Iniciar el backend con nodemon
CMD ["nodemon", "server.js"]
